#!/usr/bin/env bash
# bash script that transfer data from client to server
# Requirement:
# * The part to the file to be transfered
# * The IP of the server we want to transfer the file to
# * The username scp connects with
# * The path to the SSH

if [ $# -lt 4]
then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi
 
