#!/usr/bin/env bash
# The script is used to setup server using nginx web server

# Update package list
sudo apt-get update

# Install Nginx
sudo apt install -y nginx

# Configure Nginx to listen on port 80
sudo bash -c 'echo
"server {
    listen 80;
    listen [::]80 default_server;
    server_name _;

    location / {
        return 200 "Hello World!";
    }
}" > /etc/nginx/sites-available/default'

# Test Nginx configuration
sudo nginx -t

sudo service nginx restart
