#!/usr/bin/env bash
# script to install Nginx

#installation 
sudo apt-get update
sudo apt-get install -y nginx

#make directory in the etc system folder
mkdir /etc/nginx/html
#create an index file
touch /etc/nginx/html/index.html

echo "Hello World!" > /etc/nginx/html/index.html

printf %s "server{
       listen	80 default_server;
       listen 	[::]:80 default_server;
       root	/etc/nginx/html;
       index	index.html index.htm;
}" > /etc/nginx/sites-available/default

service nginx restart
