#!/usr/bin/env bash
# The script is used to setup server using nginx web server

# Update package list
sudo apt-get update

# Install Nginx
sudo apt install -y nginx

# Configure Nginx to listen on port 80
sudo bash -c 'cat << EOF > /etc/nginx/sites-available/default
server {
    listen 80;
    server_name _;

    location / {
        return 200 "Hello World!";
    }
}
EOF'

# Test Nginx configuration
sudo nginx -t

# Reload Nginx (since systemctl can't be used)
sudo service nginx restart
