#!/usr/bin/env bash
# script to redirect server using the nginx webserver

# Update package list
sudo apt update

# Install Nginx
sudo apt install -y nginx

# Configure Nginx to listen on port 80
sudo sed -i '/server_name _;/a \\n    location /redirect_me {\n        return 301 https://www.example.com;\n    }' /etc/nginx/sites-available/default

# Test Nginx configuration
sudo nginx -t

# Reload Nginx
sudo service nginx reload
