#!/usr/bin/env bash

#upgrading ubuntun
apt-get update
#installing the nginx 
apt-get install -y nginx

#create a directory for the html file
mkdir /etc/nginx/html
# create an html file - index.html
touch /etc/nginx/html/index.html

#create content for the html file
echo "Hello World!" > /etc/nginx/html/index.html

# send the nginx configuration to 
sed -i '/location \/redirect_me {/,/}/c\    location /redirect_me {\n        return 301 https:\/\/www.youtube.com;\n    }' /etc/nginx/sites-available/default
service nginx restart
