#!/usr/bin/env bash
# Installs Nginx with given configuration

apt-get update
apt-get install -y nginx

mkdir -p /var/www/html
touch /var/www/html/index.html
echo "Alx School" > /var/www/html/index.html
touch /var/www/html/404.html
echo "Page not found" > /var/www/html/404.html

printf %s "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    add_header X-Served-By $HOSTNAME;
    root   /var/www/html;
    index  index.html index.htm;

    location /redirect_me {
        return 301 http://dalaktronix.com/;
    }

    error_page 404 /404.html;
    location /404 {
      root /var/www/html;
      internal;
    }
}" > /etc/nginx/sites-available/default
